name: Build FLauncher APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout FLauncher
        uses: actions/checkout@v6

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Check localization files
        run: |
          echo "=== All formattedDate definitions ==="
          grep -R -n -A8 -B2 '"formattedDate"' lib/l10n/ || true

      - name: Build APK
        run: flutter build apk --release

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FLauncher-APK
          path: build/app/outputs/flutter-apk/app-release.apk
